def _pick(category: str, *english_words: str) -> dict[str, dict[str, str]]:
    return {
        english: dict(MALAYALAM_WORDS[category][english])
        for english in english_words
    }


MALAYALAM_WORDS = {
    "animals": {
        "cat": {"malayalam": "പൂച്ച", "mal_roman": "poocha"},
        "dog": {"malayalam": "നായ", "mal_roman": "naaya"},
        "elephant": {"malayalam": "ആന", "mal_roman": "aana"},
        "lion": {"malayalam": "സിംഹം", "mal_roman": "simham"},
        "fish": {"malayalam": "മീൻ", "mal_roman": "meen"},
        "bird": {"malayalam": "പക്ഷി", "mal_roman": "pakshi"},
        "cow": {"malayalam": "പശു", "mal_roman": "pashu"},
        "monkey": {"malayalam": "കുരങ്ങ്", "mal_roman": "kurangu"},
        "tiger": {"malayalam": "കടുവ", "mal_roman": "kaduva"},
        "rabbit": {"malayalam": "മുയൽ", "mal_roman": "muyal"},
        "duck": {"malayalam": "താറാവ്", "mal_roman": "thaaraav"},
        "frog": {"malayalam": "തവള", "mal_roman": "thavala"},
        "horse": {"malayalam": "കുതിര", "mal_roman": "kuthira"},
        "sheep": {"malayalam": "ചെമ്മരിയാട്", "mal_roman": "chemmariyaad"},
        "hen": {"malayalam": "കോഴി", "mal_roman": "kozhi"},
        "butterfly": {"malayalam": "ശലഭം", "mal_roman": "shalabham"},
        "snake": {"malayalam": "പാമ്പ്", "mal_roman": "paampu"},
        "bear": {"malayalam": "കരടി", "mal_roman": "karadi"},
    },
    "colors": {
        "red": {"malayalam": "ചുവപ്പ്", "mal_roman": "chuvappu"},
        "blue": {"malayalam": "നീലം", "mal_roman": "neelam"},
        "green": {"malayalam": "പച്ച", "mal_roman": "pacha"},
        "yellow": {"malayalam": "മഞ്ഞ", "mal_roman": "manja"},
        "pink": {"malayalam": "ഇളംചുവപ്പ്", "mal_roman": "ilamchuvappu"},
        "white": {"malayalam": "വെള്ള", "mal_roman": "vella"},
        "black": {"malayalam": "കറുപ്പ്", "mal_roman": "karuppu"},
        "orange": {"malayalam": "ഓറഞ്ച്", "mal_roman": "oranju"},
        "purple": {"malayalam": "ഊദാ", "mal_roman": "oodha"},
        "brown": {"malayalam": "തവിട്ട്", "mal_roman": "thavittu"},
    },
    "body_parts": {
        "eye": {"malayalam": "കണ്ണ്", "mal_roman": "kannu"},
        "nose": {"malayalam": "മൂക്ക്", "mal_roman": "mookku"},
        "hand": {"malayalam": "കൈ", "mal_roman": "kai"},
        "leg": {"malayalam": "കാൽ", "mal_roman": "kaal"},
        "ear": {"malayalam": "ചെവി", "mal_roman": "chevi"},
        "mouth": {"malayalam": "വായ", "mal_roman": "vaaya"},
        "hair": {"malayalam": "മുടി", "mal_roman": "mudi"},
        "teeth": {"malayalam": "പല്ലുകൾ", "mal_roman": "pallukal"},
        "head": {"malayalam": "തല", "mal_roman": "thala"},
        "foot": {"malayalam": "പാദം", "mal_roman": "paadam"},
        "finger": {"malayalam": "വിരൽ", "mal_roman": "viral"},
        "shoulder": {"malayalam": "തോൾ", "mal_roman": "thol"},
    },
    "numbers": {
        "one": {"malayalam": "ഒന്ന്", "mal_roman": "onnu"},
        "two": {"malayalam": "രണ്ട്", "mal_roman": "randu"},
        "three": {"malayalam": "മൂന്ന്", "mal_roman": "moonnu"},
        "four": {"malayalam": "നാല്", "mal_roman": "naalu"},
        "five": {"malayalam": "അഞ്ച്", "mal_roman": "anchu"},
        "six": {"malayalam": "ആറ്", "mal_roman": "aaru"},
        "seven": {"malayalam": "ഏഴ്", "mal_roman": "ezhu"},
        "eight": {"malayalam": "എട്ട്", "mal_roman": "ettu"},
        "nine": {"malayalam": "ഒമ്പത്", "mal_roman": "ombathu"},
        "ten": {"malayalam": "പത്ത്", "mal_roman": "pathu"},
    },
    "food": {
        "apple": {"malayalam": "ആപ്പിൾ", "mal_roman": "aappil"},
        "banana": {"malayalam": "വാഴപ്പഴം", "mal_roman": "vaazhapazham"},
        "milk": {"malayalam": "പാൽ", "mal_roman": "paal"},
        "rice": {"malayalam": "ചോറ്", "mal_roman": "choru"},
        "water": {"malayalam": "വെള്ളം", "mal_roman": "vellam"},
        "mango": {"malayalam": "മാമ്പഴം", "mal_roman": "maampazham"},
        "egg": {"malayalam": "മുട്ട", "mal_roman": "mutta"},
        "bread": {"malayalam": "ബ്രെഡ്", "mal_roman": "bred"},
        "grapes": {"malayalam": "മുന്തിരി", "mal_roman": "munthiri"},
        "potato": {"malayalam": "ഉരുളക്കിഴങ്ങ്", "mal_roman": "urulakkizhangu"},
        "tomato": {"malayalam": "തക്കാളി", "mal_roman": "thakkaali"},
        "sweet": {"malayalam": "മധുരം", "mal_roman": "madhuram"},
    },
    "common_objects": {
        "ball": {"malayalam": "പന്ത്", "mal_roman": "panth"},
        "house": {"malayalam": "വീട്", "mal_roman": "veedu"},
        "book": {"malayalam": "പുസ്തകം", "mal_roman": "pusthakam"},
        "tree": {"malayalam": "മരം", "mal_roman": "maram"},
        "sun": {"malayalam": "സൂര്യൻ", "mal_roman": "sooryan"},
        "moon": {"malayalam": "ചന്ദ്രൻ", "mal_roman": "chandran"},
        "star": {"malayalam": "നക്ഷത്രം", "mal_roman": "nakshathram"},
        "flower": {"malayalam": "പൂവ്", "mal_roman": "poovu"},
        "car": {"malayalam": "കാർ", "mal_roman": "kaar"},
        "boat": {"malayalam": "പടവ്", "mal_roman": "padavu"},
        "chair": {"malayalam": "കസേര", "mal_roman": "kasera"},
        "table": {"malayalam": "മേശ", "mal_roman": "mesha"},
        "clock": {"malayalam": "ഘടികാരം", "mal_roman": "ghadikaaram"},
        "pen": {"malayalam": "പേന", "mal_roman": "pena"},
        "door": {"malayalam": "വാതിൽ", "mal_roman": "vaathil"},
    },
    "verbs": {
        "eat": {"malayalam": "കഴിക്കുക", "mal_roman": "kazhikkuka"},
        "drink": {"malayalam": "കുടിക്കുക", "mal_roman": "kudikkuka"},
        "sleep": {"malayalam": "ഉറങ്ങുക", "mal_roman": "uranguka"},
        "walk": {"malayalam": "നടക്കുക", "mal_roman": "nadakkuka"},
        "run": {"malayalam": "ഓടുക", "mal_roman": "oduka"},
        "sit": {"malayalam": "ഇരിക്കുക", "mal_roman": "irikkuka"},
        "play": {"malayalam": "കളിക്കുക", "mal_roman": "kalikkuka"},
        "jump": {"malayalam": "ചാടുക", "mal_roman": "chaaduka"},
        "read": {"malayalam": "വായിക്കുക", "mal_roman": "vaayikkuka"},
        "write": {"malayalam": "എഴുതുക", "mal_roman": "ezhuthuka"},
        "come": {"malayalam": "വരിക", "mal_roman": "varika"},
        "go": {"malayalam": "പോകുക", "mal_roman": "pokuka"},
    },
}

MALAYALAM_PHRASE_COLORS = {
    english: dict(values)
    for english, values in MALAYALAM_WORDS["colors"].items()
}

MALAYALAM_PHRASE_ANIMALS = _pick(
    "animals",
    "cat",
    "dog",
    "bird",
    "rabbit",
    "monkey",
    "duck",
    "horse",
    "cow",
    "sheep",
    "tiger",
)

MALAYALAM_PHRASE_OBJECTS = {
    "ball": {
        **MALAYALAM_WORDS["common_objects"]["ball"],
        "malayalam_obj": "പന്തിനെ",
        "mal_obj_roman": "panthine",
    },
    "car": {
        **MALAYALAM_WORDS["common_objects"]["car"],
        "malayalam_obj": "കാറിനെ",
        "mal_obj_roman": "kaarine",
    },
    "book": {
        **MALAYALAM_WORDS["common_objects"]["book"],
        "malayalam_obj": "പുസ്തകത്തെ",
        "mal_obj_roman": "pusthakatthe",
    },
    "cup": {
        "malayalam": "കപ്പ്",
        "mal_roman": "kappu",
        "malayalam_obj": "കപ്പിനെ",
        "mal_obj_roman": "kappine",
    },
    "hat": {
        "malayalam": "തൊപ്പി",
        "mal_roman": "thoppi",
        "malayalam_obj": "തൊപ്പിയെ",
        "mal_obj_roman": "thoppiye",
    },
    "shoe": {
        "malayalam": "ചെരുപ്പ്",
        "mal_roman": "cheruppu",
        "malayalam_obj": "ചെരുപ്പിനെ",
        "mal_obj_roman": "cheruppine",
    },
    "sock": {
        "malayalam": "സോക്സ്",
        "mal_roman": "soks",
        "malayalam_obj": "സോക്സിനെ",
        "mal_obj_roman": "soksine",
    },
    "kite": {
        "malayalam": "പട്ടം",
        "mal_roman": "pattam",
        "malayalam_obj": "പട്ടത്തെ",
        "mal_obj_roman": "pattatthe",
    },
    "boat": {
        **MALAYALAM_WORDS["common_objects"]["boat"],
        "malayalam_obj": "പടവിനെ",
        "mal_obj_roman": "padavine",
    },
    "drum": {
        "malayalam": "ഡ്രം",
        "mal_roman": "dram",
        "malayalam_obj": "ഡ്രമിനെ",
        "mal_obj_roman": "dramine",
    },
}

MALAYALAM_PHRASE_ANIMAL_ACTIONS = {
    "walking": {"malayalam": "നടക്കുന്നു", "mal_roman": "nadakkunnu"},
    "sleeping": {"malayalam": "ഉറങ്ങുന്നു", "mal_roman": "urangunnu"},
    "eating": {"malayalam": "കഴിക്കുന്നു", "mal_roman": "kazhikkunnu"},
    "playing": {"malayalam": "കളിക്കുന്നു", "mal_roman": "kalikkunnu"},
}

MALAYALAM_PHRASE_FOODS = {
    "apples": {
        "mal_like": "എനിക്ക് ആപ്പിൾ ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ഒരു ആപ്പിൾ വേണം",
        "mal_give": "ദയവായി എനിക്ക് ഒരു ആപ്പിൾ തരൂ",
        "mal_like_roman": "enikku aappil ishtamaan",
        "mal_want_roman": "enikku oru aappil venam",
        "mal_give_roman": "dayavaayi enikku oru aappil tharuu",
    },
    "bananas": {
        "mal_like": "എനിക്ക് വാഴപ്പഴം ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ഒരു വാഴപ്പഴം വേണം",
        "mal_give": "ദയവായി എനിക്ക് ഒരു വാഴപ്പഴം തരൂ",
        "mal_like_roman": "enikku vaazhapazham ishtamaan",
        "mal_want_roman": "enikku oru vaazhapazham venam",
        "mal_give_roman": "dayavaayi enikku oru vaazhapazham tharuu",
    },
    "milk": {
        "mal_like": "എനിക്ക് പാൽ ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് പാൽ വേണം",
        "mal_give": "ദയവായി എനിക്ക് പാൽ തരൂ",
        "mal_like_roman": "enikku paal ishtamaan",
        "mal_want_roman": "enikku paal venam",
        "mal_give_roman": "dayavaayi enikku paal tharuu",
    },
    "rice": {
        "mal_like": "എനിക്ക് ചോറ് ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ചോറ് വേണം",
        "mal_give": "ദയവായി എനിക്ക് ചോറ് തരൂ",
        "mal_like_roman": "enikku choru ishtamaan",
        "mal_want_roman": "enikku choru venam",
        "mal_give_roman": "dayavaayi enikku choru tharuu",
    },
    "mangoes": {
        "mal_like": "എനിക്ക് മാമ്പഴം ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ഒരു മാമ്പഴം വേണം",
        "mal_give": "ദയവായി എനിക്ക് ഒരു മാമ്പഴം തരൂ",
        "mal_like_roman": "enikku maampazham ishtamaan",
        "mal_want_roman": "enikku oru maampazham venam",
        "mal_give_roman": "dayavaayi enikku oru maampazham tharuu",
    },
    "bread": {
        "mal_like": "എനിക്ക് ബ്രെഡ് ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ബ്രെഡ് വേണം",
        "mal_give": "ദയവായി എനിക്ക് ബ്രെഡ് തരൂ",
        "mal_like_roman": "enikku bred ishtamaan",
        "mal_want_roman": "enikku bred venam",
        "mal_give_roman": "dayavaayi enikku bred tharuu",
    },
    "grapes": {
        "mal_like": "എനിക്ക് മുന്തിരി ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് മുന്തിരി വേണം",
        "mal_give": "ദയവായി എനിക്ക് മുന്തിരി തരൂ",
        "mal_like_roman": "enikku munthiri ishtamaan",
        "mal_want_roman": "enikku munthiri venam",
        "mal_give_roman": "dayavaayi enikku munthiri tharuu",
    },
    "potatoes": {
        "mal_like": "എനിക്ക് ഉരുളക്കിഴങ്ങ് ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ഒരു ഉരുളക്കിഴങ്ങ് വേണം",
        "mal_give": "ദയവായി എനിക്ക് ഒരു ഉരുളക്കിഴങ്ങ് തരൂ",
        "mal_like_roman": "enikku urulakkizhangu ishtamaan",
        "mal_want_roman": "enikku oru urulakkizhangu venam",
        "mal_give_roman": "dayavaayi enikku oru urulakkizhangu tharuu",
    },
    "tomatoes": {
        "mal_like": "എനിക്ക് തക്കാളി ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് ഒരു തക്കാളി വേണം",
        "mal_give": "ദയവായി എനിക്ക് ഒരു തക്കാളി തരൂ",
        "mal_like_roman": "enikku thakkaali ishtamaan",
        "mal_want_roman": "enikku oru thakkaali venam",
        "mal_give_roman": "dayavaayi enikku oru thakkaali tharuu",
    },
    "water": {
        "mal_like": "എനിക്ക് വെള്ളം ഇഷ്ടമാണ്",
        "mal_want": "എനിക്ക് വെള്ളം വേണം",
        "mal_give": "ദയവായി എനിക്ക് വെള്ളം തരൂ",
        "mal_like_roman": "enikku vellam ishtamaan",
        "mal_want_roman": "enikku vellam venam",
        "mal_give_roman": "dayavaayi enikku vellam tharuu",
    },
}

MALAYALAM_PHRASE_PEOPLE = {
    "mommy": {
        "where_mal": "അമ്മ എവിടെയാണ്?",
        "here_mal": "അമ്മ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "amma evideyaan",
        "here_mal_roman": "amma ivide undu",
    },
    "daddy": {
        "where_mal": "അച്ഛൻ എവിടെയാണ്?",
        "here_mal": "അച്ഛൻ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "achan evideyaan",
        "here_mal_roman": "achan ivide undu",
    },
    "grandma": {
        "where_mal": "അമ്മുമ്മ എവിടെയാണ്?",
        "here_mal": "അമ്മുമ്മ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "ammumma evideyaan",
        "here_mal_roman": "ammumma ivide undu",
    },
    "grandpa": {
        "where_mal": "അപ്പൂപ്പൻ എവിടെയാണ്?",
        "here_mal": "അപ്പൂപ്പൻ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "appooppan evideyaan",
        "here_mal_roman": "appooppan ivide undu",
    },
    "brother": {
        "where_mal": "ചേട്ടൻ എവിടെയാണ്?",
        "here_mal": "ചേട്ടൻ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "chettan evideyaan",
        "here_mal_roman": "chettan ivide undu",
    },
    "sister": {
        "where_mal": "ചേച്ചി എവിടെയാണ്?",
        "here_mal": "ചേച്ചി ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "chechi evideyaan",
        "here_mal_roman": "chechi ivide undu",
    },
    "baby": {
        "where_mal": "കുഞ്ഞ് എവിടെയാണ്?",
        "here_mal": "കുഞ്ഞ് ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "kunju evideyaan",
        "here_mal_roman": "kunju ivide undu",
    },
    "teacher": {
        "where_mal": "അധ്യാപകൻ എവിടെയാണ്?",
        "here_mal": "അധ്യാപകൻ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "adhyapakan evideyaan",
        "here_mal_roman": "adhyapakan ivide undu",
    },
    "friend": {
        "where_mal": "സുഹൃത്ത് എവിടെയാണ്?",
        "here_mal": "സുഹൃത്ത് ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "suhruth evideyaan",
        "here_mal_roman": "suhruth ivide undu",
    },
    "doctor": {
        "where_mal": "ഡോക്ടർ എവിടെയാണ്?",
        "here_mal": "ഡോക്ടർ ഇവിടെ ഉണ്ട്",
        "where_mal_roman": "doktar evideyaan",
        "here_mal_roman": "doktar ivide undu",
    },
}

MALAYALAM_PHRASE_BODY_PARTS = {
    "hands": {
        "wash_mal": "കൈകൾ കഴുകൂ",
        "touch_mal": "കൈകൾ തൊടൂ",
        "wash_mal_roman": "kaikal kazhukoo",
        "touch_mal_roman": "kaikal thodoo",
    },
    "feet": {
        "wash_mal": "കാലുകൾ കഴുകൂ",
        "touch_mal": "കാലുകൾ തൊടൂ",
        "wash_mal_roman": "kaalukal kazhukoo",
        "touch_mal_roman": "kaalukal thodoo",
    },
    "eyes": {
        "wash_mal": "കണ്ണുകൾ കഴുകൂ",
        "touch_mal": "കണ്ണുകൾ തൊടൂ",
        "wash_mal_roman": "kannukal kazhukoo",
        "touch_mal_roman": "kannukal thodoo",
    },
    "ears": {
        "wash_mal": "ചെവികൾ കഴുകൂ",
        "touch_mal": "ചെവികൾ തൊടൂ",
        "wash_mal_roman": "chevikal kazhukoo",
        "touch_mal_roman": "chevikal thodoo",
    },
    "nose": {
        "wash_mal": "മൂക്ക് കഴുകൂ",
        "touch_mal": "മൂക്ക് തൊടൂ",
        "wash_mal_roman": "mookku kazhukoo",
        "touch_mal_roman": "mookku thodoo",
    },
    "mouth": {
        "wash_mal": "വായ കഴുകൂ",
        "touch_mal": "വായ തൊടൂ",
        "wash_mal_roman": "vaaya kazhukoo",
        "touch_mal_roman": "vaaya thodoo",
    },
    "hair": {
        "wash_mal": "മുടി കഴുകൂ",
        "touch_mal": "മുടി തൊടൂ",
        "wash_mal_roman": "mudi kazhukoo",
        "touch_mal_roman": "mudi thodoo",
    },
    "head": {
        "wash_mal": "തല കഴുകൂ",
        "touch_mal": "തല തൊടൂ",
        "wash_mal_roman": "thala kazhukoo",
        "touch_mal_roman": "thala thodoo",
    },
    "tummy": {
        "wash_mal": "വയർ കഴുകൂ",
        "touch_mal": "വയർ തൊടൂ",
        "wash_mal_roman": "vayar kazhukoo",
        "touch_mal_roman": "vayar thodoo",
    },
    "teeth": {
        "wash_mal": "പല്ല് തേക്കൂ",
        "touch_mal": "പല്ലുകൾ കാണിക്കൂ",
        "wash_mal_roman": "pallu thekkoo",
        "touch_mal_roman": "pallukal kaanikkoo",
    },
}

MALAYALAM_PHRASE_ACTIVITIES = {
    "Time to eat": {
        "mal_time": "കഴിക്കാനുള്ള സമയം",
        "mal_lets": "കഴിക്കാം",
        "mal_time_roman": "kazhikkaanulla samayam",
        "mal_lets_roman": "kazhikkaam",
    },
    "Time to drink water": {
        "mal_time": "വെള്ളം കുടിക്കാനുള്ള സമയം",
        "mal_lets": "വെള്ളം കുടിക്കാം",
        "mal_time_roman": "vellam kudikkaanulla samayam",
        "mal_lets_roman": "vellam kudikkaam",
    },
    "Time to sleep": {
        "mal_time": "ഉറങ്ങാനുള്ള സമയം",
        "mal_lets": "ഉറങ്ങാം",
        "mal_time_roman": "urangaanulla samayam",
        "mal_lets_roman": "urangaam",
    },
    "Time to read": {
        "mal_time": "വായിക്കാനുള്ള സമയം",
        "mal_lets": "വായിക്കാം",
        "mal_time_roman": "vaayikkaanulla samayam",
        "mal_lets_roman": "vaayikkaam",
    },
    "Time to sing": {
        "mal_time": "പാടാനുള്ള സമയം",
        "mal_lets": "പാടാം",
        "mal_time_roman": "paadaanulla samayam",
        "mal_lets_roman": "paadaam",
    },
    "Time to dance": {
        "mal_time": "നൃത്തം ചെയ്യാനുള്ള സമയം",
        "mal_lets": "നൃത്തം ചെയ്യാം",
        "mal_time_roman": "nritham cheyyaanulla samayam",
        "mal_lets_roman": "nritham cheyyaam",
    },
    "Time to clap": {
        "mal_time": "കയ്യടി ചെയ്യാനുള്ള സമയം",
        "mal_lets": "കയ്യടി ചെയ്യാം",
        "mal_time_roman": "kaiyadi cheyyaanulla samayam",
        "mal_lets_roman": "kaiyadi cheyyaam",
    },
    "Time to wash up": {
        "mal_time": "കഴുകാനുള്ള സമയം",
        "mal_lets": "കഴുകാം",
        "mal_time_roman": "kazhukaanulla samayam",
        "mal_lets_roman": "kazhukaam",
    },
    "Time to brush your teeth": {
        "mal_time": "പല്ല് തേക്കാനുള്ള സമയം",
        "mal_lets": "പല്ല് തേക്കാം",
        "mal_time_roman": "pallu thekkaanulla samayam",
        "mal_lets_roman": "pallu thekkaam",
    },
    "Time to write": {
        "mal_time": "എഴുതാനുള്ള സമയം",
        "mal_lets": "എഴുതാം",
        "mal_time_roman": "ezhuthaanulla samayam",
        "mal_lets_roman": "ezhuthaam",
    },
}

MALAYALAM_PHRASE_COMMANDS = {
    "sit down": {
        "please_mal": "ദയവായി ഇരിക്കൂ",
        "can_mal": "നിങ്ങൾക്ക് ഇരിക്കാമോ?",
        "please_mal_roman": "dayavaayi irikkoo",
        "can_mal_roman": "ningalkku irikkaamo",
    },
    "stand up": {
        "please_mal": "ദയവായി എഴുന്നേൽക്കൂ",
        "can_mal": "നിങ്ങൾക്ക് എഴുന്നേൽക്കാമോ?",
        "please_mal_roman": "dayavaayi ezhunnelkoo",
        "can_mal_roman": "ningalkku ezhunnelkkaamo",
    },
    "come here": {
        "please_mal": "ദയവായി ഇവിടെ വരൂ",
        "can_mal": "നിങ്ങൾക്ക് ഇവിടെ വരാമോ?",
        "please_mal_roman": "dayavaayi ivide varoo",
        "can_mal_roman": "ningalkku ivide varaamo",
    },
    "go slowly": {
        "please_mal": "ദയവായി പതുക്കെ പോകൂ",
        "can_mal": "നിങ്ങൾക്ക് പതുക്കെ പോകാമോ?",
        "please_mal_roman": "dayavaayi pathukke pokoo",
        "can_mal_roman": "ningalkku pathukke pokaamo",
    },
    "jump high": {
        "please_mal": "ദയവായി ഉയരത്തിൽ ചാടൂ",
        "can_mal": "നിങ്ങൾക്ക് ഉയരത്തിൽ ചാടാമോ?",
        "please_mal_roman": "dayavaayi uyarathil chaadoo",
        "can_mal_roman": "ningalkku uyarathil chaadaamo",
    },
    "clap your hands": {
        "please_mal": "ദയവായി കയ്യടി ചെയ്യൂ",
        "can_mal": "നിങ്ങൾക്ക് കയ്യടി ചെയ്യാമോ?",
        "please_mal_roman": "dayavaayi kaiyadi cheyoo",
        "can_mal_roman": "ningalkku kaiyadi cheyyaamo",
    },
    "wave hello": {
        "please_mal": "ദയവായി ഹലോ പറയൂ",
        "can_mal": "നിങ്ങൾക്ക് ഹലോ പറയാമോ?",
        "please_mal_roman": "dayavaayi halo parayoo",
        "can_mal_roman": "ningalkku halo parayaamo",
    },
    "look up": {
        "please_mal": "ദയവായി മുകളിലേക്ക് നോക്കൂ",
        "can_mal": "നിങ്ങൾക്ക് മുകളിലേക്ക് നോക്കാമോ?",
        "please_mal_roman": "dayavaayi mugalilekku nokkoo",
        "can_mal_roman": "ningalkku mugalilekku nokkaamo",
    },
    "look down": {
        "please_mal": "ദയവായി താഴേക്ക് നോക്കൂ",
        "can_mal": "നിങ്ങൾക്ക് താഴേക്ക് നോക്കാമോ?",
        "please_mal_roman": "dayavaayi thaazhekku nokkoo",
        "can_mal_roman": "ningalkku thaazhekku nokkaamo",
    },
    "turn around": {
        "please_mal": "ദയവായി തിരിയൂ",
        "can_mal": "നിങ്ങൾക്ക് തിരിയാമോ?",
        "please_mal_roman": "dayavaayi thiriyoo",
        "can_mal_roman": "ningalkku thiriyaamo",
    },
}

MALAYALAM_PHRASE_PLACES = {
    "house": {
        "go_mal": "വീട്ടിലേക്ക് പോകൂ",
        "look_mal": "വീട് നോക്കൂ",
        "go_mal_roman": "veettilekku pokoo",
        "look_mal_roman": "veedu nokkoo",
    },
    "room": {
        "go_mal": "മുറിയിലേക്ക് പോകൂ",
        "look_mal": "മുറി നോക്കൂ",
        "go_mal_roman": "muriyilekku pokoo",
        "look_mal_roman": "muri nokkoo",
    },
    "kitchen": {
        "go_mal": "അടുക്കളയിലേക്ക് പോകൂ",
        "look_mal": "അടുക്കള നോക്കൂ",
        "go_mal_roman": "adukkalayilekku pokoo",
        "look_mal_roman": "adukkala nokkoo",
    },
    "bathroom": {
        "go_mal": "കുളിമുറിയിലേക്ക് പോകൂ",
        "look_mal": "കുളിമുറി നോക്കൂ",
        "go_mal_roman": "kulimuriyilekku pokoo",
        "look_mal_roman": "kulimuri nokkoo",
    },
    "garden": {
        "go_mal": "തോട്ടത്തിലേക്ക് പോകൂ",
        "look_mal": "തോട്ടം നോക്കൂ",
        "go_mal_roman": "thottathilekku pokoo",
        "look_mal_roman": "thottam nokkoo",
    },
    "park": {
        "go_mal": "പാർക്കിലേക്ക് പോകൂ",
        "look_mal": "പാർക്ക് നോക്കൂ",
        "go_mal_roman": "paarkkilekku pokoo",
        "look_mal_roman": "paarkku nokkoo",
    },
    "bed": {
        "go_mal": "കിടക്കയിലേക്ക് പോകൂ",
        "look_mal": "കിടക്ക നോക്കൂ",
        "go_mal_roman": "kidakkayilekku pokoo",
        "look_mal_roman": "kidakka nokkoo",
    },
    "door": {
        "go_mal": "വാതിലിലേക്ക് പോകൂ",
        "look_mal": "വാതിൽ നോക്കൂ",
        "go_mal_roman": "vaathililekku pokoo",
        "look_mal_roman": "vaathil nokkoo",
    },
    "window": {
        "go_mal": "ജാലകത്തിലേക്ക് പോകൂ",
        "look_mal": "ജാലകം നോക്കൂ",
        "go_mal_roman": "jaalakathilekku pokoo",
        "look_mal_roman": "jaalakam nokkoo",
    },
    "table": {
        "go_mal": "മേശയിലേക്ക് പോകൂ",
        "look_mal": "മേശ നോക്കൂ",
        "go_mal_roman": "meshayilekku pokoo",
        "look_mal_roman": "mesha nokkoo",
    },
}

MALAYALAM_CORE_PHRASES = {
    "Let's play": {"malayalam": "കളിക്കാം", "mal_roman": "kalikkaam"},
    "Come here": {"malayalam": "ഇവിടെ വരൂ", "mal_roman": "ivide varoo"},
    "Good morning": {"malayalam": "സുപ്രഭാതം", "mal_roman": "suprabhaatham"},
    "Good night": {"malayalam": "ശുഭ രാത്രി", "mal_roman": "shubha raathri"},
    "Run fast": {"malayalam": "വേഗത്തിൽ ഓടൂ", "mal_roman": "vegathil odoo"},
    "Pretty flower": {"malayalam": "സുന്ദരമായ പൂവ്", "mal_roman": "sundaramaaya poovu"},
    "Let's go": {"malayalam": "പോകാം", "mal_roman": "pokaam"},
    "Big elephant": {"malayalam": "വലിയ ആന", "mal_roman": "valiya aana"},
    "More please": {"malayalam": "കുറച്ച് കൂടി വേണം", "mal_roman": "kurachchu koodi venam"},
    "So yummy": {"malayalam": "വളരെ രുചിയുള്ളത്", "mal_roman": "valare ruchiyullath"},
    "Wake up": {"malayalam": "എഴുന്നേൽക്കൂ", "mal_roman": "ezhunnelkoo"},
    "Very good": {"malayalam": "വളരെ നല്ലത്", "mal_roman": "valare nallath"},
    "Thank you": {"malayalam": "നന്ദി", "mal_roman": "nandi"},
    "Please help me": {
        "malayalam": "ദയവായി എന്നെ സഹായിക്കൂ",
        "mal_roman": "dayavaayi enne sahaayikkoo",
    },
    "I am ready": {"malayalam": "ഞാൻ തയ്യാറാണ്", "mal_roman": "njaan thayyaaraanu"},
    "Well done": {"malayalam": "നന്നായി ചെയ്തു", "mal_roman": "nannaayi cheythu"},
    "Great job": {"malayalam": "വളരെ നല്ല ജോലി", "mal_roman": "valare nalla joli"},
    "Be careful": {"malayalam": "ശ്രദ്ധിക്കണം", "mal_roman": "shraddhikkanam"},
    "Slow down": {"malayalam": "പതുക്കെ പോ", "mal_roman": "pathukke po"},
    "Come with me": {"malayalam": "എന്നോടൊപ്പം വരൂ", "mal_roman": "ennodoppam varoo"},
    "Wait for me": {"malayalam": "എന്നെ കാത്തിരിക്കൂ", "mal_roman": "enne kaathirikkoo"},
    "Hold my hand": {"malayalam": "എന്റെ കൈ പിടിക്കൂ", "mal_roman": "ente kai pidikkoo"},
    "I am sorry": {"malayalam": "ക്ഷമിക്കണം", "mal_roman": "kshamikkanam"},
    "You are kind": {"malayalam": "നീ ദയയുള്ളവനാണ്", "mal_roman": "nee dayayullavanaanu"},
    "Be gentle": {"malayalam": "സാവധാനം ഇരിക്കൂ", "mal_roman": "saavadhaanam irikkoo"},
    "Share your toy": {
        "malayalam": "നിന്റെ കളിപ്പാട്ടം പങ്കിടൂ",
        "mal_roman": "ninte kalippaattam pankidoo",
    },
    "My turn please": {"malayalam": "ഇപ്പോൾ എന്റെ വരി", "mal_roman": "ippol ente vari"},
    "Your turn now": {"malayalam": "ഇപ്പോൾ നിന്റെ വരി", "mal_roman": "ippol ninte vari"},
    "Wake up now": {"malayalam": "ഇപ്പോൾ എഴുന്നേൽക്കൂ", "mal_roman": "ippol ezhunnelkoo"},
    "Time for breakfast": {
        "malayalam": "പ്രഭാതഭക്ഷണ സമയം",
        "mal_roman": "prabhaathabhakshana samayam",
    },
    "Time for lunch": {"malayalam": "ഉച്ചഭക്ഷണ സമയം", "mal_roman": "uchchabhakshana samayam"},
    "Time for dinner": {"malayalam": "അത്താഴ സമയം", "mal_roman": "aththaazha samayam"},
    "Time for bath": {"malayalam": "കുളിക്കാനുള്ള സമയം", "mal_roman": "kulikkaanulla samayam"},
    "Put on your shoes": {"malayalam": "നിന്റെ ചെരുപ്പ് ഇടൂ", "mal_roman": "ninte cheruppu idoo"},
    "Put on your socks": {"malayalam": "നിന്റെ സോക്സ് ഇടൂ", "mal_roman": "ninte soks idoo"},
    "Open the door": {"malayalam": "വാതിൽ തുറക്കൂ", "mal_roman": "vaathil thurakkoo"},
    "Close the door": {"malayalam": "വാതിൽ അടയ്ക്കൂ", "mal_roman": "vaathil adaykkoo"},
    "Pack your bag": {"malayalam": "നിന്റെ ബാഗ് തയ്യാറാക്കൂ", "mal_roman": "ninte bag thayyaarakkoo"},
    "Clean your room": {"malayalam": "നിന്റെ മുറി വൃത്തിയാക്കൂ", "mal_roman": "ninte muri vrithiyaakkoo"},
    "Pick up your toys": {
        "malayalam": "നിന്റെ കളിപ്പാട്ടങ്ങൾ എടുക്കൂ",
        "mal_roman": "ninte kalippaattangal edukkoo",
    },
    "Listen to me": {"malayalam": "എന്നെ കേൾക്കൂ", "mal_roman": "enne kelkkoo"},
    "Look at me": {"malayalam": "എന്നെ നോക്കൂ", "mal_roman": "enne nokkoo"},
}
