TAMIL_WORDS = {
    "animals": {
        "cat": {"tamil": "பூனை", "tam_roman": "poonai"},
        "dog": {"tamil": "நாய்", "tam_roman": "naai"},
        "elephant": {"tamil": "யானை", "tam_roman": "yaanai"},
        "lion": {"tamil": "சிங்கம்", "tam_roman": "singam"},
        "fish": {"tamil": "மீன்", "tam_roman": "meen"},
        "bird": {"tamil": "பறவை", "tam_roman": "paravai"},
        "cow": {"tamil": "பசு", "tam_roman": "pasu"},
        "monkey": {"tamil": "குரங்கு", "tam_roman": "kurangu"},
        "tiger": {"tamil": "புலி", "tam_roman": "puli"},
        "rabbit": {"tamil": "முயல்", "tam_roman": "muyal"},
        "duck": {"tamil": "வாத்து", "tam_roman": "vaathu"},
        "frog": {"tamil": "தவளை", "tam_roman": "thavalai"},
        "horse": {"tamil": "குதிரை", "tam_roman": "kuthirai"},
        "sheep": {"tamil": "செம்மறியாடு", "tam_roman": "semmariyaadu"},
        "hen": {"tamil": "கோழி", "tam_roman": "kozhi"},
        "butterfly": {"tamil": "பட்டாம்பூச்சி", "tam_roman": "pattaampoochi"},
        "snake": {"tamil": "பாம்பு", "tam_roman": "paambu"},
        "bear": {"tamil": "கரடி", "tam_roman": "karadi"},
    },
    "colors": {
        "red": {"tamil": "சிவப்பு", "tam_roman": "sivappu"},
        "blue": {"tamil": "நீலம்", "tam_roman": "neelam"},
        "green": {"tamil": "பச்சை", "tam_roman": "pachai"},
        "yellow": {"tamil": "மஞ்சள்", "tam_roman": "manjal"},
        "pink": {"tamil": "இளஞ்சிவப்பு", "tam_roman": "ilanchivappu"},
        "white": {"tamil": "வெள்ளை", "tam_roman": "vellai"},
        "black": {"tamil": "கருப்பு", "tam_roman": "karuppu"},
        "orange": {"tamil": "ஆரஞ்சு", "tam_roman": "aaranju"},
        "purple": {"tamil": "ஊதா", "tam_roman": "oodha"},
        "brown": {"tamil": "பழுப்பு", "tam_roman": "pazhuppu"},
    },
    "body_parts": {
        "eye": {"tamil": "கண்", "tam_roman": "kan"},
        "nose": {"tamil": "மூக்கு", "tam_roman": "mookku"},
        "hand": {"tamil": "கை", "tam_roman": "kai"},
        "leg": {"tamil": "கால்", "tam_roman": "kaal"},
        "ear": {"tamil": "காது", "tam_roman": "kaadhu"},
        "mouth": {"tamil": "வாய்", "tam_roman": "vaai"},
        "hair": {"tamil": "முடி", "tam_roman": "mudi"},
        "teeth": {"tamil": "பற்கள்", "tam_roman": "parkal"},
        "head": {"tamil": "தலை", "tam_roman": "thalai"},
        "foot": {"tamil": "பாதம்", "tam_roman": "paadham"},
        "finger": {"tamil": "விரல்", "tam_roman": "viral"},
        "shoulder": {"tamil": "தோள்", "tam_roman": "thol"},
    },
    "numbers": {
        "one": {"tamil": "ஒன்று", "tam_roman": "onru"},
        "two": {"tamil": "இரண்டு", "tam_roman": "irandu"},
        "three": {"tamil": "மூன்று", "tam_roman": "moonru"},
        "four": {"tamil": "நான்கு", "tam_roman": "naangu"},
        "five": {"tamil": "ஐந்து", "tam_roman": "aindhu"},
        "six": {"tamil": "ஆறு", "tam_roman": "aaru"},
        "seven": {"tamil": "ஏழு", "tam_roman": "ezhu"},
        "eight": {"tamil": "எட்டு", "tam_roman": "ettu"},
        "nine": {"tamil": "ஒன்பது", "tam_roman": "onbadhu"},
        "ten": {"tamil": "பத்து", "tam_roman": "paththu"},
    },
    "food": {
        "apple": {"tamil": "ஆப்பிள்", "tam_roman": "aappil"},
        "banana": {"tamil": "வாழைப்பழம்", "tam_roman": "vaazhaipazham"},
        "milk": {"tamil": "பால்", "tam_roman": "paal"},
        "rice": {"tamil": "சாதம்", "tam_roman": "saadham"},
        "water": {"tamil": "தண்ணீர்", "tam_roman": "thanneer"},
        "mango": {"tamil": "மாம்பழம்", "tam_roman": "maampazham"},
        "egg": {"tamil": "முட்டை", "tam_roman": "muttai"},
        "bread": {"tamil": "ரொட்டி", "tam_roman": "rotti"},
        "grapes": {"tamil": "திராட்சை", "tam_roman": "thiraatchai"},
        "potato": {"tamil": "உருளைக்கிழங்கு", "tam_roman": "urulaikkizhangu"},
        "tomato": {"tamil": "தக்காளி", "tam_roman": "thakkaali"},
        "sweet": {"tamil": "இனிப்பு", "tam_roman": "inippu"},
    },
    "common_objects": {
        "ball": {"tamil": "பந்து", "tam_roman": "pandhu"},
        "house": {"tamil": "வீடு", "tam_roman": "veedu"},
        "book": {"tamil": "புத்தகம்", "tam_roman": "puththagam"},
        "tree": {"tamil": "மரம்", "tam_roman": "maram"},
        "sun": {"tamil": "சூரியன்", "tam_roman": "sooriyan"},
        "moon": {"tamil": "நிலா", "tam_roman": "nilaa"},
        "star": {"tamil": "நட்சத்திரம்", "tam_roman": "natchaththiram"},
        "flower": {"tamil": "பூ", "tam_roman": "poo"},
        "car": {"tamil": "கார்", "tam_roman": "kaar"},
        "boat": {"tamil": "படகு", "tam_roman": "padagu"},
        "chair": {"tamil": "நாற்காலி", "tam_roman": "naarkkaali"},
        "table": {"tamil": "மேசை", "tam_roman": "mesai"},
        "clock": {"tamil": "கடிகாரம்", "tam_roman": "kadigaaram"},
        "pen": {"tamil": "பேனா", "tam_roman": "penaa"},
        "door": {"tamil": "கதவு", "tam_roman": "kathavu"},
    },
    "verbs": {
        "eat": {"tamil": "சாப்பிடு", "tam_roman": "saappidu"},
        "drink": {"tamil": "குடி", "tam_roman": "kudi"},
        "sleep": {"tamil": "தூங்கு", "tam_roman": "thoongu"},
        "walk": {"tamil": "நடப்பது", "tam_roman": "nadappadhu"},
        "run": {"tamil": "ஓடு", "tam_roman": "odu"},
        "sit": {"tamil": "உட்கார்", "tam_roman": "utkaar"},
        "play": {"tamil": "விளையாடு", "tam_roman": "vilayaadu"},
        "jump": {"tamil": "குதி", "tam_roman": "kudhi"},
        "read": {"tamil": "படி", "tam_roman": "padi"},
        "write": {"tamil": "எழுது", "tam_roman": "ezhudhu"},
        "come": {"tamil": "வா", "tam_roman": "vaa"},
        "go": {"tamil": "போ", "tam_roman": "po"},
    },
}

TAMIL_PHRASE_COLORS = {
    english: dict(TAMIL_WORDS["colors"][english])
    for english in TAMIL_WORDS["colors"]
}

TAMIL_PHRASE_ANIMALS = {
    english: dict(TAMIL_WORDS["animals"][english])
    for english in (
        "cat",
        "dog",
        "bird",
        "rabbit",
        "monkey",
        "duck",
        "horse",
        "cow",
        "sheep",
        "tiger",
    )
}

TAMIL_PHRASE_OBJECTS = {
    "ball": {
        **TAMIL_WORDS["common_objects"]["ball"],
        "tamil_obj": "பந்தை",
        "tam_obj_roman": "pandhai",
    },
    "car": {
        **TAMIL_WORDS["common_objects"]["car"],
        "tamil_obj": "காரை",
        "tam_obj_roman": "kaarai",
    },
    "book": {
        **TAMIL_WORDS["common_objects"]["book"],
        "tamil_obj": "புத்தகத்தை",
        "tam_obj_roman": "puththagaththai",
    },
    "cup": {
        "tamil": "கோப்பை",
        "tam_roman": "koppai",
        "tamil_obj": "கோப்பையை",
        "tam_obj_roman": "koppaiyai",
    },
    "hat": {
        "tamil": "தொப்பி",
        "tam_roman": "thoppi",
        "tamil_obj": "தொப்பியை",
        "tam_obj_roman": "thoppiyai",
    },
    "shoe": {
        "tamil": "காலணி",
        "tam_roman": "kaalani",
        "tamil_obj": "காலணியை",
        "tam_obj_roman": "kaalaniyai",
    },
    "sock": {
        "tamil": "காலுறை",
        "tam_roman": "kaalurai",
        "tamil_obj": "காலுறையை",
        "tam_obj_roman": "kaaluraiyai",
    },
    "kite": {
        "tamil": "பட்டம்",
        "tam_roman": "pattam",
        "tamil_obj": "பட்டத்தை",
        "tam_obj_roman": "pattaththai",
    },
    "boat": {
        **TAMIL_WORDS["common_objects"]["boat"],
        "tamil_obj": "படகை",
        "tam_obj_roman": "padagai",
    },
    "drum": {
        "tamil": "முரசு",
        "tam_roman": "murasu",
        "tamil_obj": "முரசை",
        "tam_obj_roman": "murasai",
    },
}

TAMIL_PHRASE_ANIMAL_ACTIONS = {
    "walking": {"tamil": "நடக்கிறது", "tam_roman": "nadakkiradhu"},
    "sleeping": {"tamil": "தூங்குகிறது", "tam_roman": "thoongugiradhu"},
    "eating": {"tamil": "சாப்பிடுகிறது", "tam_roman": "saappidugiradhu"},
    "playing": {"tamil": "விளையாடுகிறது", "tam_roman": "vilayaadugiradhu"},
}

TAMIL_PHRASE_FOODS = {
    "apples": {
        "tam_like": "எனக்கு ஆப்பிள் பிடிக்கும்",
        "tam_want": "எனக்கு ஒரு ஆப்பிள் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு ஒரு ஆப்பிள் கொடுங்கள்",
        "tam_like_roman": "enakku aappil pidikkum",
        "tam_want_roman": "enakku oru aappil vendum",
        "tam_give_roman": "thayavuseydhu enakku oru aappil kodungal",
    },
    "bananas": {
        "tam_like": "எனக்கு வாழைப்பழம் பிடிக்கும்",
        "tam_want": "எனக்கு ஒரு வாழைப்பழம் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு ஒரு வாழைப்பழம் கொடுங்கள்",
        "tam_like_roman": "enakku vaazhaipazham pidikkum",
        "tam_want_roman": "enakku oru vaazhaipazham vendum",
        "tam_give_roman": "thayavuseydhu enakku oru vaazhaipazham kodungal",
    },
    "milk": {
        "tam_like": "எனக்கு பால் பிடிக்கும்",
        "tam_want": "எனக்கு பால் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு பால் கொடுங்கள்",
        "tam_like_roman": "enakku paal pidikkum",
        "tam_want_roman": "enakku paal vendum",
        "tam_give_roman": "thayavuseydhu enakku paal kodungal",
    },
    "rice": {
        "tam_like": "எனக்கு சாதம் பிடிக்கும்",
        "tam_want": "எனக்கு சாதம் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு சாதம் கொடுங்கள்",
        "tam_like_roman": "enakku saadham pidikkum",
        "tam_want_roman": "enakku saadham vendum",
        "tam_give_roman": "thayavuseydhu enakku saadham kodungal",
    },
    "mangoes": {
        "tam_like": "எனக்கு மாம்பழம் பிடிக்கும்",
        "tam_want": "எனக்கு ஒரு மாம்பழம் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு ஒரு மாம்பழம் கொடுங்கள்",
        "tam_like_roman": "enakku maampazham pidikkum",
        "tam_want_roman": "enakku oru maampazham vendum",
        "tam_give_roman": "thayavuseydhu enakku oru maampazham kodungal",
    },
    "bread": {
        "tam_like": "எனக்கு ரொட்டி பிடிக்கும்",
        "tam_want": "எனக்கு ரொட்டி வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு ரொட்டி கொடுங்கள்",
        "tam_like_roman": "enakku rotti pidikkum",
        "tam_want_roman": "enakku rotti vendum",
        "tam_give_roman": "thayavuseydhu enakku rotti kodungal",
    },
    "grapes": {
        "tam_like": "எனக்கு திராட்சை பிடிக்கும்",
        "tam_want": "எனக்கு திராட்சை வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு திராட்சை கொடுங்கள்",
        "tam_like_roman": "enakku thiraatchai pidikkum",
        "tam_want_roman": "enakku thiraatchai vendum",
        "tam_give_roman": "thayavuseydhu enakku thiraatchai kodungal",
    },
    "potatoes": {
        "tam_like": "எனக்கு உருளைக்கிழங்கு பிடிக்கும்",
        "tam_want": "எனக்கு உருளைக்கிழங்கு வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு உருளைக்கிழங்கு கொடுங்கள்",
        "tam_like_roman": "enakku urulaikkizhangu pidikkum",
        "tam_want_roman": "enakku urulaikkizhangu vendum",
        "tam_give_roman": "thayavuseydhu enakku urulaikkizhangu kodungal",
    },
    "tomatoes": {
        "tam_like": "எனக்கு தக்காளி பிடிக்கும்",
        "tam_want": "எனக்கு தக்காளி வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு தக்காளி கொடுங்கள்",
        "tam_like_roman": "enakku thakkaali pidikkum",
        "tam_want_roman": "enakku thakkaali vendum",
        "tam_give_roman": "thayavuseydhu enakku thakkaali kodungal",
    },
    "water": {
        "tam_like": "எனக்கு தண்ணீர் பிடிக்கும்",
        "tam_want": "எனக்கு தண்ணீர் வேண்டும்",
        "tam_give": "தயவுசெய்து எனக்கு தண்ணீர் கொடுங்கள்",
        "tam_like_roman": "enakku thanneer pidikkum",
        "tam_want_roman": "enakku thanneer vendum",
        "tam_give_roman": "thayavuseydhu enakku thanneer kodungal",
    },
}

TAMIL_PHRASE_PEOPLE = {
    "mommy": {
        "where_tam": "அம்மா எங்கே இருக்கிறார்?",
        "here_tam": "அம்மா இங்கே இருக்கிறார்",
        "where_tam_roman": "amma enge irukkiraar",
        "here_tam_roman": "amma inge irukkiraar",
    },
    "daddy": {
        "where_tam": "அப்பா எங்கே இருக்கிறார்?",
        "here_tam": "அப்பா இங்கே இருக்கிறார்",
        "where_tam_roman": "appa enge irukkiraar",
        "here_tam_roman": "appa inge irukkiraar",
    },
    "grandma": {
        "where_tam": "பாட்டி எங்கே இருக்கிறார்?",
        "here_tam": "பாட்டி இங்கே இருக்கிறார்",
        "where_tam_roman": "paatti enge irukkiraar",
        "here_tam_roman": "paatti inge irukkiraar",
    },
    "grandpa": {
        "where_tam": "தாத்தா எங்கே இருக்கிறார்?",
        "here_tam": "தாத்தா இங்கே இருக்கிறார்",
        "where_tam_roman": "thaaththa enge irukkiraar",
        "here_tam_roman": "thaaththa inge irukkiraar",
    },
    "brother": {
        "where_tam": "அண்ணா எங்கே இருக்கிறார்?",
        "here_tam": "அண்ணா இங்கே இருக்கிறார்",
        "where_tam_roman": "annaa enge irukkiraar",
        "here_tam_roman": "annaa inge irukkiraar",
    },
    "sister": {
        "where_tam": "அக்கா எங்கே இருக்கிறார்?",
        "here_tam": "அக்கா இங்கே இருக்கிறார்",
        "where_tam_roman": "akkaa enge irukkiraar",
        "here_tam_roman": "akkaa inge irukkiraar",
    },
    "baby": {
        "where_tam": "குழந்தை எங்கே இருக்கிறது?",
        "here_tam": "குழந்தை இங்கே இருக்கிறது",
        "where_tam_roman": "kuzhanthai enge irukkiradhu",
        "here_tam_roman": "kuzhanthai inge irukkiradhu",
    },
    "teacher": {
        "where_tam": "ஆசிரியர் எங்கே இருக்கிறார்?",
        "here_tam": "ஆசிரியர் இங்கே இருக்கிறார்",
        "where_tam_roman": "aasiriyar enge irukkiraar",
        "here_tam_roman": "aasiriyar inge irukkiraar",
    },
    "friend": {
        "where_tam": "நண்பன் எங்கே இருக்கிறார்?",
        "here_tam": "நண்பன் இங்கே இருக்கிறார்",
        "where_tam_roman": "nanban enge irukkiraar",
        "here_tam_roman": "nanban inge irukkiraar",
    },
    "doctor": {
        "where_tam": "மருத்துவர் எங்கே இருக்கிறார்?",
        "here_tam": "மருத்துவர் இங்கே இருக்கிறார்",
        "where_tam_roman": "maruththuvar enge irukkiraar",
        "here_tam_roman": "maruththuvar inge irukkiraar",
    },
}

TAMIL_PHRASE_BODY_PARTS = {
    "hands": {
        "wash_tam": "உங்கள் கைகளை கழுவுங்கள்",
        "touch_tam": "உங்கள் கைகளை தொடுங்கள்",
        "wash_tam_roman": "ungal kaigalai kazhuvungal",
        "touch_tam_roman": "ungal kaigalai thodungal",
    },
    "feet": {
        "wash_tam": "உங்கள் கால்களை கழுவுங்கள்",
        "touch_tam": "உங்கள் கால்களை தொடுங்கள்",
        "wash_tam_roman": "ungal kaalkalai kazhuvungal",
        "touch_tam_roman": "ungal kaalkalai thodungal",
    },
    "eyes": {
        "wash_tam": "உங்கள் கண்களை கழுவுங்கள்",
        "touch_tam": "உங்கள் கண்களை தொடுங்கள்",
        "wash_tam_roman": "ungal kangalai kazhuvungal",
        "touch_tam_roman": "ungal kangalai thodungal",
    },
    "ears": {
        "wash_tam": "உங்கள் காதுகளை கழுவுங்கள்",
        "touch_tam": "உங்கள் காதுகளை தொடுங்கள்",
        "wash_tam_roman": "ungal kaadhugalai kazhuvungal",
        "touch_tam_roman": "ungal kaadhugalai thodungal",
    },
    "nose": {
        "wash_tam": "உங்கள் மூக்கை கழுவுங்கள்",
        "touch_tam": "உங்கள் மூக்கை தொடுங்கள்",
        "wash_tam_roman": "ungal mookkai kazhuvungal",
        "touch_tam_roman": "ungal mookkai thodungal",
    },
    "mouth": {
        "wash_tam": "உங்கள் வாயை கழுவுங்கள்",
        "touch_tam": "உங்கள் வாயை தொடுங்கள்",
        "wash_tam_roman": "ungal vaayai kazhuvungal",
        "touch_tam_roman": "ungal vaayai thodungal",
    },
    "hair": {
        "wash_tam": "உங்கள் முடியை கழுவுங்கள்",
        "touch_tam": "உங்கள் முடியை தொடுங்கள்",
        "wash_tam_roman": "ungal mudiyai kazhuvungal",
        "touch_tam_roman": "ungal mudiyai thodungal",
    },
    "head": {
        "wash_tam": "உங்கள் தலையை கழுவுங்கள்",
        "touch_tam": "உங்கள் தலையை தொடுங்கள்",
        "wash_tam_roman": "ungal thalaiyai kazhuvungal",
        "touch_tam_roman": "ungal thalaiyai thodungal",
    },
    "tummy": {
        "wash_tam": "உங்கள் வயிற்றை கழுவுங்கள்",
        "touch_tam": "உங்கள் வயிற்றை தொடுங்கள்",
        "wash_tam_roman": "ungal vayittrai kazhuvungal",
        "touch_tam_roman": "ungal vayittrai thodungal",
    },
    "teeth": {
        "wash_tam": "உங்கள் பற்களை துலக்குங்கள்",
        "touch_tam": "உங்கள் பற்களை காட்டுங்கள்",
        "wash_tam_roman": "ungal parkalai thulakkungal",
        "touch_tam_roman": "ungal parkalai kaattungal",
    },
}

TAMIL_PHRASE_ACTIVITIES = {
    "Time to eat": {
        "tam_time": "சாப்பிட நேரம்",
        "tam_lets": "சாப்பிடலாம்",
        "tam_time_roman": "saappida neram",
        "tam_lets_roman": "saappidalaam",
    },
    "Time to drink water": {
        "tam_time": "தண்ணீர் குடிக்க நேரம்",
        "tam_lets": "தண்ணீர் குடிக்கலாம்",
        "tam_time_roman": "thanneer kudikka neram",
        "tam_lets_roman": "thanneer kudikkalaam",
    },
    "Time to sleep": {
        "tam_time": "தூங்க நேரம்",
        "tam_lets": "தூங்கலாம்",
        "tam_time_roman": "thoonga neram",
        "tam_lets_roman": "thoongalaam",
    },
    "Time to read": {
        "tam_time": "படிக்க நேரம்",
        "tam_lets": "படிக்கலாம்",
        "tam_time_roman": "padikka neram",
        "tam_lets_roman": "padikkalaam",
    },
    "Time to sing": {
        "tam_time": "பாட நேரம்",
        "tam_lets": "பாடலாம்",
        "tam_time_roman": "paada neram",
        "tam_lets_roman": "paadalaam",
    },
    "Time to dance": {
        "tam_time": "ஆட நேரம்",
        "tam_lets": "ஆடலாம்",
        "tam_time_roman": "aada neram",
        "tam_lets_roman": "aadalaam",
    },
    "Time to clap": {
        "tam_time": "கைத்தட்ட நேரம்",
        "tam_lets": "கைத்தட்டலாம்",
        "tam_time_roman": "kaitthatta neram",
        "tam_lets_roman": "kaitthattalaam",
    },
    "Time to wash up": {
        "tam_time": "குளிக்க நேரம்",
        "tam_lets": "குளிக்கலாம்",
        "tam_time_roman": "kulikka neram",
        "tam_lets_roman": "kulikkalaam",
    },
    "Time to brush your teeth": {
        "tam_time": "பல் துலக்க நேரம்",
        "tam_lets": "பல் துலக்கலாம்",
        "tam_time_roman": "pal thulakka neram",
        "tam_lets_roman": "pal thulakkalaam",
    },
    "Time to write": {
        "tam_time": "எழுத நேரம்",
        "tam_lets": "எழுதலாம்",
        "tam_time_roman": "ezhutha neram",
        "tam_lets_roman": "ezhuthalaam",
    },
}

TAMIL_PHRASE_COMMANDS = {
    "sit down": {
        "please_tam": "தயவுசெய்து உட்காருங்கள்",
        "can_tam": "நீங்கள் உட்கார முடியுமா?",
        "please_tam_roman": "thayavuseydhu utkaarungal",
        "can_tam_roman": "neengal utkaara mudiyumaa",
    },
    "stand up": {
        "please_tam": "தயவுசெய்து எழுந்திருங்கள்",
        "can_tam": "நீங்கள் எழுந்திருக்க முடியுமா?",
        "please_tam_roman": "thayavuseydhu ezhundhirungal",
        "can_tam_roman": "neengal ezhundhirukka mudiyumaa",
    },
    "come here": {
        "please_tam": "தயவுசெய்து இங்கே வாருங்கள்",
        "can_tam": "நீங்கள் இங்கே வர முடியுமா?",
        "please_tam_roman": "thayavuseydhu inge vaarungal",
        "can_tam_roman": "neengal inge vara mudiyumaa",
    },
    "go slowly": {
        "please_tam": "தயவுசெய்து மெதுவாக செல்லுங்கள்",
        "can_tam": "நீங்கள் மெதுவாக செல்ல முடியுமா?",
        "please_tam_roman": "thayavuseydhu medhuvaaga sellungal",
        "can_tam_roman": "neengal medhuvaaga sella mudiyumaa",
    },
    "jump high": {
        "please_tam": "தயவுசெய்து உயரமாக குதிக்கவும்",
        "can_tam": "நீங்கள் உயரமாக குதிக்க முடியுமா?",
        "please_tam_roman": "thayavuseydhu uyaramaaga kudhikkavum",
        "can_tam_roman": "neengal uyaramaaga kudhikka mudiyumaa",
    },
    "clap your hands": {
        "please_tam": "தயவுசெய்து கைத்தட்டுங்கள்",
        "can_tam": "நீங்கள் கைத்தட்ட முடியுமா?",
        "please_tam_roman": "thayavuseydhu kaittattungal",
        "can_tam_roman": "neengal kaitthatta mudiyumaa",
    },
    "wave hello": {
        "please_tam": "தயவுசெய்து ஹலோ சொல்லுங்கள்",
        "can_tam": "நீங்கள் ஹலோ சொல்ல முடியுமா?",
        "please_tam_roman": "thayavuseydhu halo sollungal",
        "can_tam_roman": "neengal halo solla mudiyumaa",
    },
    "look up": {
        "please_tam": "தயவுசெய்து மேலே பாருங்கள்",
        "can_tam": "நீங்கள் மேலே பார்க்க முடியுமா?",
        "please_tam_roman": "thayavuseydhu mele paarungal",
        "can_tam_roman": "neengal mele paarka mudiyumaa",
    },
    "look down": {
        "please_tam": "தயவுசெய்து கீழே பாருங்கள்",
        "can_tam": "நீங்கள் கீழே பார்க்க முடியுமா?",
        "please_tam_roman": "thayavuseydhu keezhe paarungal",
        "can_tam_roman": "neengal keezhe paarka mudiyumaa",
    },
    "turn around": {
        "please_tam": "தயவுசெய்து திரும்புங்கள்",
        "can_tam": "நீங்கள் திரும்ப முடியுமா?",
        "please_tam_roman": "thayavuseydhu thirumbungal",
        "can_tam_roman": "neengal thirumba mudiyumaa",
    },
}

TAMIL_PHRASE_PLACES = {
    "house": {
        "go_tam": "வீட்டுக்குச் செல்லுங்கள்",
        "look_tam": "வீட்டை பாருங்கள்",
        "go_tam_roman": "veettukkuch sellungal",
        "look_tam_roman": "veettai paarungal",
    },
    "room": {
        "go_tam": "அறைக்குச் செல்லுங்கள்",
        "look_tam": "அறையை பாருங்கள்",
        "go_tam_roman": "araikkuch sellungal",
        "look_tam_roman": "araiyai paarungal",
    },
    "kitchen": {
        "go_tam": "சமையலறைக்குச் செல்லுங்கள்",
        "look_tam": "சமையலறையை பாருங்கள்",
        "go_tam_roman": "samayalaraikkuch sellungal",
        "look_tam_roman": "samayalaraiyai paarungal",
    },
    "bathroom": {
        "go_tam": "குளியலறைக்குச் செல்லுங்கள்",
        "look_tam": "குளியலறையை பாருங்கள்",
        "go_tam_roman": "kuliyalarakkuch sellungal",
        "look_tam_roman": "kuliyalaraiyai paarungal",
    },
    "garden": {
        "go_tam": "தோட்டத்துக்குச் செல்லுங்கள்",
        "look_tam": "தோட்டத்தை பாருங்கள்",
        "go_tam_roman": "thottaththukkuch sellungal",
        "look_tam_roman": "thottaththai paarungal",
    },
    "park": {
        "go_tam": "பூங்காவுக்குச் செல்லுங்கள்",
        "look_tam": "பூங்காவை பாருங்கள்",
        "go_tam_roman": "poongaavukkuch sellungal",
        "look_tam_roman": "poongaavai paarungal",
    },
    "bed": {
        "go_tam": "படுக்கைக்கு செல்லுங்கள்",
        "look_tam": "படுக்கையை பாருங்கள்",
        "go_tam_roman": "padukkaikku sellungal",
        "look_tam_roman": "padukkaiyai paarungal",
    },
    "door": {
        "go_tam": "கதவுக்குச் செல்லுங்கள்",
        "look_tam": "கதவை பாருங்கள்",
        "go_tam_roman": "kathavukkuch sellungal",
        "look_tam_roman": "kathavai paarungal",
    },
    "window": {
        "go_tam": "ஜன்னலுக்குச் செல்லுங்கள்",
        "look_tam": "ஜன்னலை பாருங்கள்",
        "go_tam_roman": "jannalukkuch sellungal",
        "look_tam_roman": "jannalai paarungal",
    },
    "table": {
        "go_tam": "மேசைக்குச் செல்லுங்கள்",
        "look_tam": "மேசையை பாருங்கள்",
        "go_tam_roman": "mesaikkuch sellungal",
        "look_tam_roman": "mesaiyai paarungal",
    },
}

TAMIL_CORE_PHRASES = {
    "Let's play": {"tamil": "விளையாடலாம்", "tam_roman": "vilayaadalam"},
    "Come here": {"tamil": "இங்கே வா", "tam_roman": "inge vaa"},
    "Good morning": {"tamil": "காலை வணக்கம்", "tam_roman": "kaalai vanakkam"},
    "Good night": {"tamil": "இனிய இரவு", "tam_roman": "iniya iravu"},
    "Run fast": {"tamil": "வேகமாக ஓடு", "tam_roman": "vegamaaga odu"},
    "Pretty flower": {"tamil": "அழகான பூ", "tam_roman": "azhagana poo"},
    "Let's go": {"tamil": "போகலாம்", "tam_roman": "pogalaam"},
    "Big elephant": {"tamil": "பெரிய யானை", "tam_roman": "periya yaanai"},
    "More please": {"tamil": "இன்னும் வேண்டும்", "tam_roman": "innum vendum"},
    "So yummy": {"tamil": "ரொம்ப சுவையாக இருக்கிறது", "tam_roman": "romba suvaiyaaga irukkiradhu"},
    "Wake up": {"tamil": "எழுந்திரு", "tam_roman": "ezhundhiru"},
    "Very good": {"tamil": "மிகவும் நல்லது", "tam_roman": "migavum nalladhu"},
    "Thank you": {"tamil": "நன்றி", "tam_roman": "nandri"},
    "Please help me": {
        "tamil": "தயவுசெய்து எனக்கு உதவுங்கள்",
        "tam_roman": "thayavuseydhu enakku udhavungal",
    },
    "I am ready": {"tamil": "நான் தயார்", "tam_roman": "naan thayaar"},
    "Well done": {"tamil": "நல்லா செய்தாய்", "tam_roman": "nallaa seydhai"},
    "Great job": {"tamil": "அருமையான வேலை", "tam_roman": "arumaiyaana velai"},
    "Be careful": {"tamil": "கவனமாக இரு", "tam_roman": "gavanamaaga iru"},
    "Slow down": {"tamil": "மெதுவாக போ", "tam_roman": "medhuvaaga po"},
    "Come with me": {"tamil": "என்னுடன் வா", "tam_roman": "ennudan vaa"},
    "Wait for me": {"tamil": "எனக்காக காத்திரு", "tam_roman": "enakkaaga kaaththiru"},
    "Hold my hand": {"tamil": "என் கையை பிடி", "tam_roman": "en kaiyai pidi"},
    "I am sorry": {"tamil": "என்னை மன்னிக்கவும்", "tam_roman": "ennai mannikkavum"},
    "You are kind": {"tamil": "நீ அன்பானவன்", "tam_roman": "nee anbaanavan"},
    "Be gentle": {"tamil": "மெதுவாக இரு", "tam_roman": "medhuvaaga iru"},
    "Share your toy": {
        "tamil": "உன் பொம்மையை பகிர்ந்து கொள்",
        "tam_roman": "un pommaiyai pagirndhu kol",
    },
    "My turn please": {"tamil": "இப்போது என் முறை", "tam_roman": "ippodhu en murai"},
    "Your turn now": {"tamil": "இப்போது உன் முறை", "tam_roman": "ippodhu un murai"},
    "Wake up now": {"tamil": "இப்போதே எழுந்திரு", "tam_roman": "ippodhe ezhundhiru"},
    "Time for breakfast": {"tamil": "காலை உணவு நேரம்", "tam_roman": "kaalai unavu neram"},
    "Time for lunch": {"tamil": "மதிய உணவு நேரம்", "tam_roman": "madhhiya unavu neram"},
    "Time for dinner": {"tamil": "இரவு உணவு நேரம்", "tam_roman": "iravu unavu neram"},
    "Time for bath": {"tamil": "குளிக்கும் நேரம்", "tam_roman": "kulikkum neram"},
    "Put on your shoes": {"tamil": "உன் காலணியை போடு", "tam_roman": "un kaalaniyai podu"},
    "Put on your socks": {"tamil": "உன் காலுறையை போடு", "tam_roman": "un kaaluraiyai podu"},
    "Open the door": {"tamil": "கதவை திற", "tam_roman": "kathavai thira"},
    "Close the door": {"tamil": "கதவை மூடு", "tam_roman": "kathavai moodu"},
    "Pack your bag": {"tamil": "உன் பையை தயார் செய்", "tam_roman": "un paiyai thayaar sei"},
    "Clean your room": {"tamil": "உன் அறையை சுத்தம் செய்", "tam_roman": "un araiyai suththam sei"},
    "Pick up your toys": {"tamil": "உன் பொம்மைகளை எடு", "tam_roman": "un pommaigalai edu"},
    "Listen to me": {"tamil": "நான் சொல்வதை கேள்", "tam_roman": "naan solvadhai kel"},
    "Look at me": {"tamil": "என்னை பார்", "tam_roman": "ennai paar"},
}
